export const JWT_SECRET = 'JWT_SECRET';
export const JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET';

export const JWT_EXPIRES_IN = 'JWT_EXPIRES_IN';
export const JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN';

export const PORT = 'PORT';
